/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author ElPsy
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonitoresPanel = new javax.swing.JPanel();
        jButtonNewMonitor = new javax.swing.JButton();
        jButtonUpdateMonitor = new javax.swing.JButton();
        jButtonDeleteMonitor = new javax.swing.JButton();
        ButtonCerrar = new javax.swing.JButton();
        jGestionLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMonitores = new javax.swing.JTable();
        jSociosPanel = new javax.swing.JPanel();
        ButtonNuevo1 = new javax.swing.JButton();
        ButtonBaja1 = new javax.swing.JButton();
        ButtonUpdate1 = new javax.swing.JButton();
        ButtonCerrar1 = new javax.swing.JButton();
        jGestionLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMonitoresPanel.setPreferredSize(new java.awt.Dimension(955, 370));

        jButtonNewMonitor.setText("Nuevo Monitor");
        jButtonNewMonitor.setActionCommand("ButtonNewMonitor");

        jButtonUpdateMonitor.setText("Actualiza Monitor");
        jButtonUpdateMonitor.setActionCommand("ButtonUpdateMonitor");

        jButtonDeleteMonitor.setText("Elimina Monitor");
        jButtonDeleteMonitor.setToolTipText("");
        jButtonDeleteMonitor.setActionCommand("ButtonRemoveMonitor");

        ButtonCerrar.setText("Salir");
        ButtonCerrar.setActionCommand("CerrarCommand");

        jGestionLabel2.setText("Gestion De Monitores");
        jGestionLabel2.setPreferredSize(new java.awt.Dimension(124, 16));

        jTableMonitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane3.setViewportView(jTableMonitores);

        javax.swing.GroupLayout jMonitoresPanelLayout = new javax.swing.GroupLayout(jMonitoresPanel);
        jMonitoresPanel.setLayout(jMonitoresPanelLayout);
        jMonitoresPanelLayout.setHorizontalGroup(
            jMonitoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMonitoresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMonitoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMonitoresPanelLayout.createSequentialGroup()
                        .addComponent(jButtonNewMonitor)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateMonitor)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteMonitor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                        .addComponent(ButtonCerrar)
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane3)
                    .addGroup(jMonitoresPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jGestionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jMonitoresPanelLayout.setVerticalGroup(
            jMonitoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMonitoresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGestionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jMonitoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewMonitor)
                    .addComponent(jButtonUpdateMonitor)
                    .addComponent(jButtonDeleteMonitor)
                    .addComponent(ButtonCerrar))
                .addGap(22, 22, 22))
        );

        jSociosPanel.setPreferredSize(new java.awt.Dimension(955, 370));

        ButtonNuevo1.setText("jButton1");

        ButtonBaja1.setText("jButton2");

        ButtonUpdate1.setText("jButton3");

        ButtonCerrar1.setText("Salir");
        ButtonCerrar1.setActionCommand("CerrarCommand");

        jGestionLabel1.setText("Gestion De Socios");
        jGestionLabel1.setPreferredSize(new java.awt.Dimension(124, 16));

        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTableSocios);

        javax.swing.GroupLayout jSociosPanelLayout = new javax.swing.GroupLayout(jSociosPanel);
        jSociosPanel.setLayout(jSociosPanelLayout);
        jSociosPanelLayout.setHorizontalGroup(
            jSociosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSociosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jSociosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSociosPanelLayout.createSequentialGroup()
                        .addComponent(ButtonNuevo1)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBaja1)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonUpdate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 594, Short.MAX_VALUE)
                        .addComponent(ButtonCerrar1)
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                    .addGroup(jSociosPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jGestionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jSociosPanelLayout.setVerticalGroup(
            jSociosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSociosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGestionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jSociosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNuevo1)
                    .addComponent(ButtonBaja1)
                    .addComponent(ButtonUpdate1)
                    .addComponent(ButtonCerrar1))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(jSociosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(157, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jMonitoresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(459, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jSociosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jMonitoresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(197, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBaja1;
    public javax.swing.JButton ButtonCerrar;
    public javax.swing.JButton ButtonCerrar1;
    private javax.swing.JButton ButtonNuevo1;
    private javax.swing.JButton ButtonUpdate1;
    private javax.swing.JButton jButtonDeleteMonitor;
    public javax.swing.JButton jButtonNewMonitor;
    private javax.swing.JButton jButtonUpdateMonitor;
    public javax.swing.JLabel jGestionLabel1;
    public javax.swing.JLabel jGestionLabel2;
    public javax.swing.JPanel jMonitoresPanel;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JPanel jSociosPanel;
    public javax.swing.JTable jTableMonitores;
    public javax.swing.JTable jTableSocios;
    // End of variables declaration//GEN-END:variables
}
