/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class SocioPanelLayout extends javax.swing.JPanel {

    /**
     * Creates new form PanelTableLayout
     */
    public SocioPanelLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNewSocio = new javax.swing.JButton();
        jButtonUpdateSocio = new javax.swing.JButton();
        jButtonDeleteSocio = new javax.swing.JButton();
        ButtonCerrar1 = new javax.swing.JButton();
        jGestionLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();
        jButtonConfigureSocio = new javax.swing.JButton();

        jButtonNewSocio.setText("Nuevo Socio");
        jButtonNewSocio.setActionCommand("ButtonNewSocio");
        jButtonNewSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSocioActionPerformed(evt);
            }
        });

        jButtonUpdateSocio.setText("Borrar Socio");
        jButtonUpdateSocio.setActionCommand("ButtonDeleteSocio");
        jButtonUpdateSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateSocioActionPerformed(evt);
            }
        });

        jButtonDeleteSocio.setText("Actualiza Socio");
        jButtonDeleteSocio.setActionCommand("ButtonUpdateSocio");
        jButtonDeleteSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSocioActionPerformed(evt);
            }
        });

        ButtonCerrar1.setText("Salir");
        ButtonCerrar1.setActionCommand("CerrarCommand");

        jGestionLabel1.setText("Gestion De Socios");
        jGestionLabel1.setPreferredSize(new java.awt.Dimension(124, 16));

        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTableSocios);

        jButtonConfigureSocio.setText("Configuracion de Actividades");
        jButtonConfigureSocio.setActionCommand("ButtonConfigureActivity");
        jButtonConfigureSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigureSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNewSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConfigureSocio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCerrar1)
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jGestionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGestionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewSocio)
                    .addComponent(jButtonUpdateSocio)
                    .addComponent(jButtonDeleteSocio)
                    .addComponent(ButtonCerrar1)
                    .addComponent(jButtonConfigureSocio))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewSocioActionPerformed

    private void jButtonUpdateSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateSocioActionPerformed

    private void jButtonConfigureSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigureSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfigureSocioActionPerformed

    private void jButtonDeleteSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteSocioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonCerrar1;
    public javax.swing.JButton jButtonConfigureSocio;
    public javax.swing.JButton jButtonDeleteSocio;
    public javax.swing.JButton jButtonNewSocio;
    public javax.swing.JButton jButtonUpdateSocio;
    public javax.swing.JLabel jGestionLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableSocios;
    // End of variables declaration//GEN-END:variables
}
