/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
 

import java.awt.Color;

/**
 *
 * @author ElPsy
 */
public class ColaFrame extends java.awt.Frame {

    /**
     * Creates new form AppFrame
     */
    public ColaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException, Exception {
        int sizeCola = 10;

        ColaFrame frame = new ColaFrame();

        frame.setSize(800, 600);
        frame.setBackground(Color.BLACK);

        CanvasCola canvas = new CanvasCola(frame.getSize(), sizeCola);
        frame.add(canvas);

        frame.setVisible(true);

        ColaLenta cola = new ColaLenta(sizeCola, canvas);

        Thread consumidor = new Consumidor(cola);
        Thread productor = new Productor(cola);

        productor.start();
        Thread.sleep(5000);
        consumidor.start();

        productor.join();
        consumidor.join();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
